import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Readable} from 'node:stream';
import {createHmac} from 'node:crypto';
import {createWhatsApp} from '../whatsapp.mjs';
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());let sends=0;const env={WHATSAPP_PHONE_NUMBER_ID:'123',WHATSAPP_APP_SECRET:'secret',WHATSAPP_VERIFY_TOKEN:'verify',WHATSAPP_ACCESS_TOKEN:'token',OPENAI_API_KEY:'key',OPENAI_MODEL:'model'};const w=createWhatsApp({db,env,json:(r,status,data)=>Object.assign(r,{status,data}),body:async r=>r.data,fail:(status,message)=>Object.assign(Error(message),{status}),audit:()=>{},generateImpl:async()=> 'Please contact Dr Rohit.',fetchImpl:async()=>{sends++;return {ok:true,json:async()=>({messages:[{id:'outbound'}]})}}});return {db,w,env,get sends(){return sends;}};}
function request(f,payload,bad=false){const raw=JSON.stringify(payload),req=Readable.from([Buffer.from(raw)]);req.method='POST';req.headers={'x-hub-signature-256':bad?'bad':'sha256='+createHmac('sha256',f.env.WHATSAPP_APP_SECRET).update(raw).digest('hex')};return req;}
const event=(phone='123',timestamp=Date.now()/1000)=>({object:'whatsapp_business_account',entry:[{changes:[{field:'messages',value:{metadata:{phone_number_id:phone},messages:[{id:'msg1',from:'919876543210',timestamp:String(Math.floor(timestamp)),type:'text',text:{body:'Clinic appointment?'}}]}}]}]});
test('signed webhook, number filtering, deduplication and owner-only inbox',async t=>{const f=fixture(t);await assert.rejects(f.w.publicRoute(request(f,event(),true),{},'/api/whatsapp/webhook'),{status:401});await f.w.publicRoute(request(f,event('other')),{},'/api/whatsapp/webhook');assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM whatsapp_inbox').get().n,0);await f.w.publicRoute(request(f,event()),{},'/api/whatsapp/webhook');await f.w.publicRoute(request(f,event()),{},'/api/whatsapp/webhook');assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM whatsapp_inbox').get().n,1);await assert.rejects(f.w.route({method:'GET'},{},'/api/whatsapp/inbox','staff'),{status:403});});
test('approval required; draft generation never sends; duplicate sending blocked',async t=>{const f=fixture(t);await f.w.publicRoute(request(f,event()),{},'/api/whatsapp/webhook');await f.w.route({method:'POST'}, {},'/api/whatsapp/msg1/draft','owner');assert.equal(f.sends,0);await assert.rejects(f.w.route({method:'POST',data:{text:'Hello'}},{},'/api/whatsapp/msg1/send','owner'),{status:400});await f.w.route({method:'POST',data:{text:'Hello',approved:true}},{},'/api/whatsapp/msg1/send','owner');assert.equal(f.sends,1);await assert.rejects(f.w.route({method:'POST',data:{text:'Hello',approved:true}},{},'/api/whatsapp/msg1/send','owner'),{status:409});});
test('expired replies and staff handoff block sending',async t=>{const f=fixture(t);await f.w.publicRoute(request(f,event('123',Date.now()/1000-90000)),{},'/api/whatsapp/webhook');await assert.rejects(f.w.route({method:'POST',data:{text:'Hello',approved:true}},{},'/api/whatsapp/msg1/send','owner'),{status:409});f.db.prepare('UPDATE whatsapp_inbox SET received_at=?').run(Date.now());await f.w.route({method:'POST'},{},'/api/whatsapp/msg1/handoff','owner');await assert.rejects(f.w.route({method:'POST',data:{text:'Hello',approved:true}},{},'/api/whatsapp/msg1/send','owner'),{status:409});assert.equal(f.sends,0);});
